#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-cli
Version  : 1.0
Release  : 3
URL      : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.0/commons-cli-1.0.jar
Source0  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.0/commons-cli-1.0.jar
Source1  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.0/commons-cli-1.0.pom
Source2  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
Source3  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.2/commons-cli-1.2.pom
Source4  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar
Source5  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.pom
Source6  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
Source7  : https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.1 Apache-2.0
Requires: mvn-commons-cli-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-cli package.
Group: Data

%description data
data components for the mvn-commons-cli package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.3.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.3.1
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.3.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.4
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.4
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/commons-cli/commons-cli/1.4


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.0/commons-cli-1.0.jar
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.0/commons-cli-1.0.pom
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.pom
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.jar
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.3.1/commons-cli-1.3.1.pom
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar
/usr/share/java/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.pom
